package com.example.miquelcastanys.androidchallenge

object TestConstants {
    val FIRST_PAGE = "[" +
            "  {" +
            "    \"id\": 2399148," +
            "    \"name\": \"absurdity\"," +
            "    \"full_name\": \"xing/absurdity\"," +
            "    \"owner\": {" +
            "      \"login\": \"xing\"," +
            "      \"id\": 27901," +
            "      \"avatar_url\": \"https://avatars2.githubusercontent.com/u/27901?v=4\"," +
            "      \"gravatar_id\": \"\"," +
            "      \"url\": \"https://api.github.com/users/xing\"," +
            "      \"html_url\": \"https://github.com/xing\"," +
            "      \"followers_url\": \"https://api.github.com/users/xing/followers\"," +
            "      \"following_url\": \"https://api.github.com/users/xing/following{/other_user}\"," +
            "      \"gists_url\": \"https://api.github.com/users/xing/gists{/gist_id}\"," +
            "      \"starred_url\": \"https://api.github.com/users/xing/starred{/owner}{/repo}\"," +
            "      \"subscriptions_url\": \"https://api.github.com/users/xing/subscriptions\"," +
            "      \"organizations_url\": \"https://api.github.com/users/xing/orgs\"," +
            "      \"repos_url\": \"https://api.github.com/users/xing/repos\"," +
            "      \"events_url\": \"https://api.github.com/users/xing/events{/privacy}\"," +
            "      \"received_events_url\": \"https://api.github.com/users/xing/received_events\"," +
            "      \"type\": \"Organization\"," +
            "      \"site_admin\": false" +
            "    }," +
            "    \"private\": false," +
            "    \"html_url\": \"https://github.com/xing/absurdity\"," +
            "    \"description\": \"Absurdly simple AB testing framework\"," +
            "    \"fork\": false," +
            "    \"url\": \"https://api.github.com/repos/xing/absurdity\"," +
            "    \"forks_url\": \"https://api.github.com/repos/xing/absurdity/forks\"," +
            "    \"keys_url\": \"https://api.github.com/repos/xing/absurdity/keys{/key_id}\"," +
            "    \"collaborators_url\": \"https://api.github.com/repos/xing/absurdity/collaborators{/collaborator}\"," +
            "    \"teams_url\": \"https://api.github.com/repos/xing/absurdity/teams\"," +
            "    \"hooks_url\": \"https://api.github.com/repos/xing/absurdity/hooks\"," +
            "    \"issue_events_url\": \"https://api.github.com/repos/xing/absurdity/issues/events{/number}\"," +
            "    \"events_url\": \"https://api.github.com/repos/xing/absurdity/events\"," +
            "    \"assignees_url\": \"https://api.github.com/repos/xing/absurdity/assignees{/user}\"," +
            "    \"branches_url\": \"https://api.github.com/repos/xing/absurdity/branches{/branch}\"," +
            "    \"tags_url\": \"https://api.github.com/repos/xing/absurdity/tags\"," +
            "    \"blobs_url\": \"https://api.github.com/repos/xing/absurdity/git/blobs{/sha}\"," +
            "    \"git_tags_url\": \"https://api.github.com/repos/xing/absurdity/git/tags{/sha}\"," +
            "    \"git_refs_url\": \"https://api.github.com/repos/xing/absurdity/git/refs{/sha}\"," +
            "    \"trees_url\": \"https://api.github.com/repos/xing/absurdity/git/trees{/sha}\"," +
            "    \"statuses_url\": \"https://api.github.com/repos/xing/absurdity/statuses/{sha}\"," +
            "    \"languages_url\": \"https://api.github.com/repos/xing/absurdity/languages\"," +
            "    \"stargazers_url\": \"https://api.github.com/repos/xing/absurdity/stargazers\"," +
            "    \"contributors_url\": \"https://api.github.com/repos/xing/absurdity/contributors\"," +
            "    \"subscribers_url\": \"https://api.github.com/repos/xing/absurdity/subscribers\"," +
            "    \"subscription_url\": \"https://api.github.com/repos/xing/absurdity/subscription\"," +
            "    \"commits_url\": \"https://api.github.com/repos/xing/absurdity/commits{/sha}\"," +
            "    \"git_commits_url\": \"https://api.github.com/repos/xing/absurdity/git/commits{/sha}\"," +
            "    \"comments_url\": \"https://api.github.com/repos/xing/absurdity/comments{/number}\"," +
            "    \"issue_comment_url\": \"https://api.github.com/repos/xing/absurdity/issues/comments{/number}\"," +
            "    \"contents_url\": \"https://api.github.com/repos/xing/absurdity/contents/{+path}\"," +
            "    \"compare_url\": \"https://api.github.com/repos/xing/absurdity/compare/{base}...{head}\"," +
            "    \"merges_url\": \"https://api.github.com/repos/xing/absurdity/merges\"," +
            "    \"archive_url\": \"https://api.github.com/repos/xing/absurdity/{archive_format}{/ref}\"," +
            "    \"downloads_url\": \"https://api.github.com/repos/xing/absurdity/downloads\"," +
            "    \"issues_url\": \"https://api.github.com/repos/xing/absurdity/issues{/number}\"," +
            "    \"pulls_url\": \"https://api.github.com/repos/xing/absurdity/pulls{/number}\"," +
            "    \"milestones_url\": \"https://api.github.com/repos/xing/absurdity/milestones{/number}\"," +
            "    \"notifications_url\": \"https://api.github.com/repos/xing/absurdity/notifications{?since,all,participating}\"," +
            "    \"labels_url\": \"https://api.github.com/repos/xing/absurdity/labels{/name}\"," +
            "    \"releases_url\": \"https://api.github.com/repos/xing/absurdity/releases{/id}\"," +
            "    \"deployments_url\": \"https://api.github.com/repos/xing/absurdity/deployments\"," +
            "    \"created_at\": \"2011-09-16T12:34:03Z\"," +
            "    \"updated_at\": \"2017-10-27T23:25:23Z\"," +
            "    \"pushed_at\": \"2012-06-09T17:25:45Z\"," +
            "    \"git_url\": \"git://github.com/xing/absurdity.git\"," +
            "    \"ssh_url\": \"git@github.com:xing/absurdity.git\"," +
            "    \"clone_url\": \"https://github.com/xing/absurdity.git\"," +
            "    \"svn_url\": \"https://github.com/xing/absurdity\"," +
            "    \"homepage\": \"\"," +
            "    \"size\": 154," +
            "    \"stargazers_count\": 61," +
            "    \"watchers_count\": 61," +
            "    \"language\": \"Ruby\"," +
            "    \"has_issues\": true," +
            "    \"has_projects\": true," +
            "    \"has_downloads\": true," +
            "    \"has_wiki\": true," +
            "    \"has_pages\": false," +
            "    \"forks_count\": 7," +
            "    \"mirror_url\": null," +
            "    \"archived\": false," +
            "    \"open_issues_count\": 1," +
            "    \"license\": null," +
            "    \"forks\": 7," +
            "    \"open_issues\": 1," +
            "    \"watchers\": 61," +
            "    \"default_branch\": \"master\"" +
            "  }," +
            "  {" +
            "    \"id\": 8337219," +
            "    \"name\": \"AFQuickLookView\"," +
            "    \"full_name\": \"xing/AFQuickLookView\"," +
            "    \"owner\": {" +
            "      \"login\": \"xing\"," +
            "      \"id\": 27901," +
            "      \"avatar_url\": \"https://avatars2.githubusercontent.com/u/27901?v=4\"," +
            "      \"gravatar_id\": \"\"," +
            "      \"url\": \"https://api.github.com/users/xing\"," +
            "      \"html_url\": \"https://github.com/xing\"," +
            "      \"followers_url\": \"https://api.github.com/users/xing/followers\"," +
            "      \"following_url\": \"https://api.github.com/users/xing/following{/other_user}\"," +
            "      \"gists_url\": \"https://api.github.com/users/xing/gists{/gist_id}\"," +
            "      \"starred_url\": \"https://api.github.com/users/xing/starred{/owner}{/repo}\"," +
            "      \"subscriptions_url\": \"https://api.github.com/users/xing/subscriptions\"," +
            "      \"organizations_url\": \"https://api.github.com/users/xing/orgs\"," +
            "      \"repos_url\": \"https://api.github.com/users/xing/repos\"," +
            "      \"events_url\": \"https://api.github.com/users/xing/events{/privacy}\"," +
            "      \"received_events_url\": \"https://api.github.com/users/xing/received_events\"," +
            "      \"type\": \"Organization\"," +
            "      \"site_admin\": false" +
            "    }," +
            "    \"private\": false," +
            "    \"html_url\": \"https://github.com/xing/AFQuickLookView\"," +
            "    \"description\": \"AFNetworking Extension for document previews of remote files\"," +
            "    \"fork\": false," +
            "    \"url\": \"https://api.github.com/repos/xing/AFQuickLookView\"," +
            "    \"forks_url\": \"https://api.github.com/repos/xing/AFQuickLookView/forks\"," +
            "    \"keys_url\": \"https://api.github.com/repos/xing/AFQuickLookView/keys{/key_id}\"," +
            "    \"collaborators_url\": \"https://api.github.com/repos/xing/AFQuickLookView/collaborators{/collaborator}\"," +
            "    \"teams_url\": \"https://api.github.com/repos/xing/AFQuickLookView/teams\"," +
            "    \"hooks_url\": \"https://api.github.com/repos/xing/AFQuickLookView/hooks\"," +
            "    \"issue_events_url\": \"https://api.github.com/repos/xing/AFQuickLookView/issues/events{/number}\"," +
            "    \"events_url\": \"https://api.github.com/repos/xing/AFQuickLookView/events\"," +
            "    \"assignees_url\": \"https://api.github.com/repos/xing/AFQuickLookView/assignees{/user}\"," +
            "    \"branches_url\": \"https://api.github.com/repos/xing/AFQuickLookView/branches{/branch}\"," +
            "    \"tags_url\": \"https://api.github.com/repos/xing/AFQuickLookView/tags\"," +
            "    \"blobs_url\": \"https://api.github.com/repos/xing/AFQuickLookView/git/blobs{/sha}\"," +
            "    \"git_tags_url\": \"https://api.github.com/repos/xing/AFQuickLookView/git/tags{/sha}\"," +
            "    \"git_refs_url\": \"https://api.github.com/repos/xing/AFQuickLookView/git/refs{/sha}\"," +
            "    \"trees_url\": \"https://api.github.com/repos/xing/AFQuickLookView/git/trees{/sha}\"," +
            "    \"statuses_url\": \"https://api.github.com/repos/xing/AFQuickLookView/statuses/{sha}\"," +
            "    \"languages_url\": \"https://api.github.com/repos/xing/AFQuickLookView/languages\"," +
            "    \"stargazers_url\": \"https://api.github.com/repos/xing/AFQuickLookView/stargazers\"," +
            "    \"contributors_url\": \"https://api.github.com/repos/xing/AFQuickLookView/contributors\"," +
            "    \"subscribers_url\": \"https://api.github.com/repos/xing/AFQuickLookView/subscribers\"," +
            "    \"subscription_url\": \"https://api.github.com/repos/xing/AFQuickLookView/subscription\"," +
            "    \"commits_url\": \"https://api.github.com/repos/xing/AFQuickLookView/commits{/sha}\"," +
            "    \"git_commits_url\": \"https://api.github.com/repos/xing/AFQuickLookView/git/commits{/sha}\"," +
            "    \"comments_url\": \"https://api.github.com/repos/xing/AFQuickLookView/comments{/number}\"," +
            "    \"issue_comment_url\": \"https://api.github.com/repos/xing/AFQuickLookView/issues/comments{/number}\"," +
            "    \"contents_url\": \"https://api.github.com/repos/xing/AFQuickLookView/contents/{+path}\"," +
            "    \"compare_url\": \"https://api.github.com/repos/xing/AFQuickLookView/compare/{base}...{head}\"," +
            "    \"merges_url\": \"https://api.github.com/repos/xing/AFQuickLookView/merges\"," +
            "    \"archive_url\": \"https://api.github.com/repos/xing/AFQuickLookView/{archive_format}{/ref}\"," +
            "    \"downloads_url\": \"https://api.github.com/repos/xing/AFQuickLookView/downloads\"," +
            "    \"issues_url\": \"https://api.github.com/repos/xing/AFQuickLookView/issues{/number}\"," +
            "    \"pulls_url\": \"https://api.github.com/repos/xing/AFQuickLookView/pulls{/number}\"," +
            "    \"milestones_url\": \"https://api.github.com/repos/xing/AFQuickLookView/milestones{/number}\"," +
            "    \"notifications_url\": \"https://api.github.com/repos/xing/AFQuickLookView/notifications{?since,all,participating}\"," +
            "    \"labels_url\": \"https://api.github.com/repos/xing/AFQuickLookView/labels{/name}\"," +
            "    \"releases_url\": \"https://api.github.com/repos/xing/AFQuickLookView/releases{/id}\"," +
            "    \"deployments_url\": \"https://api.github.com/repos/xing/AFQuickLookView/deployments\"," +
            "    \"created_at\": \"2013-02-21T14:54:12Z\"," +
            "    \"updated_at\": \"2017-12-04T03:29:30Z\"," +
            "    \"pushed_at\": \"2013-04-05T20:12:06Z\"," +
            "    \"git_url\": \"git://github.com/xing/AFQuickLookView.git\"," +
            "    \"ssh_url\": \"git@github.com:xing/AFQuickLookView.git\"," +
            "    \"clone_url\": \"https://github.com/xing/AFQuickLookView.git\"," +
            "    \"svn_url\": \"https://github.com/xing/AFQuickLookView\"," +
            "    \"homepage\": null," +
            "    \"size\": 231," +
            "    \"stargazers_count\": 76," +
            "    \"watchers_count\": 76," +
            "    \"language\": \"Objective-C\"," +
            "    \"has_issues\": true," +
            "    \"has_projects\": true," +
            "    \"has_downloads\": true," +
            "    \"has_wiki\": true," +
            "    \"has_pages\": false," +
            "    \"forks_count\": 7," +
            "    \"mirror_url\": null," +
            "    \"archived\": false," +
            "    \"open_issues_count\": 10," +
            "    \"license\": {" +
            "      \"key\": \"mit\"," +
            "      \"name\": \"MIT License\"," +
            "      \"spdx_id\": \"MIT\"," +
            "      \"url\": \"https://api.github.com/licenses/mit\"" +
            "    }," +
            "    \"forks\": 7," +
            "    \"open_issues\": 10," +
            "    \"watchers\": 76," +
            "    \"default_branch\": \"master\"" +
            "  }" +
            "]"

    val ERROR_MESSAGE = "Not Found"
}